#!/bin/bash
# Generate GitHub Actions workflow configuration from Terraform outputs
# and automatically update .github/workflows/deploy.yml

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IAAC_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ROOT_DIR="$(cd "$IAAC_DIR/.." && pwd)"
WORKFLOW_FILE="$ROOT_DIR/.github/workflows/deploy.yml"

cd "$IAAC_DIR"

# Check if Terraform has been initialized
if [ ! -d ".terraform" ]; then
  echo "Error: Terraform not initialized. Run './scripts/init.sh' first"
  exit 1
fi

# Load environment
if [ -f ".iaac.env" ]; then
  set -a
  source ".iaac.env"
  set +a
else
  echo "Warning: .iaac.env not found. Some values may be missing."
fi

# Get Terraform outputs
echo "📊 Fetching Terraform outputs..."
DEV_WIF_PROVIDER=$(terraform output -raw dev_wif_provider 2>/dev/null || echo "")
STAGING_WIF_PROVIDER=$(terraform output -raw staging_wif_provider 2>/dev/null || echo "")
PROD_WIF_PROVIDER=$(terraform output -raw prod_wif_provider 2>/dev/null || echo "")

DEV_SA_EMAIL=$(terraform output -raw dev_service_account_email 2>/dev/null || echo "")
STAGING_SA_EMAIL=$(terraform output -raw staging_service_account_email 2>/dev/null || echo "")
PROD_SA_EMAIL=$(terraform output -raw prod_service_account_email 2>/dev/null || echo "")

# Validate that we have all required values
if [ -z "$DEV_WIF_PROVIDER" ] || [ -z "$STAGING_WIF_PROVIDER" ] || [ -z "$PROD_WIF_PROVIDER" ]; then
  echo "Error: Missing WIF provider values. Run 'terraform apply' first."
  exit 1
fi

if [ -z "$DEV_SA_EMAIL" ] || [ -z "$STAGING_SA_EMAIL" ] || [ -z "$PROD_SA_EMAIL" ]; then
  echo "Error: Missing service account email values. Run 'terraform apply' first."
  exit 1
fi

REPLACEMENT_FILE="$(mktemp)"
cleanup() {
  rm -f "$REPLACEMENT_FILE"
}
trap cleanup EXIT

# Generate the replacement content (WITHOUT the marker lines; awk will keep the markers)
cat > "$REPLACEMENT_FILE" <<EOF
          # This section is auto-generated by iaac/scripts/generate-workflow-config.sh
          # Do not edit manually - run the script to update these values from Terraform outputs
          if [ "\${{ github.ref_name }}" = "${GITHUB_BRANCH_DEV:-develop}" ]; then
            # --- Development environment (GCP dev project) ---
            echo "gcp_project_id=${GCP_PROJECT_ID_DEV}" >> "\$GITHUB_OUTPUT"
            echo "ar_repository=${AR_REPOSITORY_DEV:-dev-rates}" >> "\$GITHUB_OUTPUT"
            echo "cloud_run_service_app=${CLOUD_RUN_SERVICE_APP_DEV:-rates-app-dev}" >> "\$GITHUB_OUTPUT"
            echo "cloud_run_service_auth_app=${CLOUD_RUN_SERVICE_AUTH_APP_DEV:-rates-auth-app-dev}" >> "\$GITHUB_OUTPUT"
            echo "wif_provider=${DEV_WIF_PROVIDER}" >> "\$GITHUB_OUTPUT"
            echo "wif_service_account=${DEV_SA_EMAIL}" >> "\$GITHUB_OUTPUT"
            echo "github_environment=development" >> "\$GITHUB_OUTPUT"
          elif [ "\${{ github.ref_name }}" = "${GITHUB_BRANCH_STAGING:-staging}" ]; then
            # --- Staging environment (GCP staging project) ---
            echo "gcp_project_id=${GCP_PROJECT_ID_STAGING}" >> "\$GITHUB_OUTPUT"
            echo "ar_repository=${AR_REPOSITORY_STAGING:-staging-rates}" >> "\$GITHUB_OUTPUT"
            echo "cloud_run_service_app=${CLOUD_RUN_SERVICE_APP_STAGING:-rates-app-staging}" >> "\$GITHUB_OUTPUT"
            echo "cloud_run_service_auth_app=${CLOUD_RUN_SERVICE_AUTH_APP_STAGING:-rates-auth-app-staging}" >> "\$GITHUB_OUTPUT"
            echo "wif_provider=${STAGING_WIF_PROVIDER}" >> "\$GITHUB_OUTPUT"
            echo "wif_service_account=${STAGING_SA_EMAIL}" >> "\$GITHUB_OUTPUT"
            echo "github_environment=staging" >> "\$GITHUB_OUTPUT"
          else
            # --- Production (main) ---
            echo "gcp_project_id=${GCP_PROJECT_ID_PROD}" >> "\$GITHUB_OUTPUT"
            echo "ar_repository=${AR_REPOSITORY_PROD:-rates}" >> "\$GITHUB_OUTPUT"
            echo "cloud_run_service_app=${CLOUD_RUN_SERVICE_APP_PROD:-rates-app}" >> "\$GITHUB_OUTPUT"
            echo "cloud_run_service_auth_app=${CLOUD_RUN_SERVICE_AUTH_APP_PROD:-rates-auth-app}" >> "\$GITHUB_OUTPUT"
            echo "wif_provider=${PROD_WIF_PROVIDER}" >> "\$GITHUB_OUTPUT"
            echo "wif_service_account=${PROD_SA_EMAIL}" >> "\$GITHUB_OUTPUT"
            echo "github_environment=production" >> "\$GITHUB_OUTPUT"
          fi
EOF

# Check if workflow file exists
if [ ! -f "$WORKFLOW_FILE" ]; then
  echo "Error: Workflow file not found at $WORKFLOW_FILE"
  exit 1
fi

# Check if markers exist
if ! grep -q "<<TERRAFORM_VALUES_START>>" "$WORKFLOW_FILE"; then
  echo "Error: Marker <<TERRAFORM_VALUES_START>> not found in $WORKFLOW_FILE"
  echo "Please add the markers to identify where to insert Terraform values."
  exit 1
fi

if ! grep -q "<<TERRAFORM_VALUES_END>>" "$WORKFLOW_FILE"; then
  echo "Error: Marker <<TERRAFORM_VALUES_END>> not found in $WORKFLOW_FILE"
  echo "Please add the markers to identify where to insert Terraform values."
  exit 1
fi

# Create a temporary file for updated workflow
TEMP_FILE="$(mktemp)"

# Use awk to replace content between markers by splicing in the replacement file.
# (Avoids passing multiline strings via -v, which breaks on macOS awk.)
awk -v repl_file="$REPLACEMENT_FILE" '
  /<<TERRAFORM_VALUES_START>>/ {
    print
    while ((getline line < repl_file) > 0) print line
    close(repl_file)
    skip = 1
    next
  }
  /<<TERRAFORM_VALUES_END>>/ {
    skip = 0
    print
    next
  }
  skip != 1 { print }
' "$WORKFLOW_FILE" > "$TEMP_FILE"

# Verify the replacement worked
if ! grep -q "<<TERRAFORM_VALUES_START>>" "$TEMP_FILE"; then
  echo "Error: Replacement failed - markers not found in output"
  exit 1
fi

# Backup original file
cp "$WORKFLOW_FILE" "${WORKFLOW_FILE}.backup"

# Replace original with updated content
mv "$TEMP_FILE" "$WORKFLOW_FILE"

echo "✓ Updated workflow file automatically"
echo "  Location: $WORKFLOW_FILE"
echo "  Backup: ${WORKFLOW_FILE}.backup"
echo ""
echo "📋 Updated values:"
echo ""
echo "Development:"
echo "  Project ID: ${GCP_PROJECT_ID_DEV}"
echo "  WIF Provider: ${DEV_WIF_PROVIDER}"
echo "  Service Account: ${DEV_SA_EMAIL}"
echo ""
echo "Staging:"
echo "  Project ID: ${GCP_PROJECT_ID_STAGING}"
echo "  WIF Provider: ${STAGING_WIF_PROVIDER}"
echo "  Service Account: ${STAGING_SA_EMAIL}"
echo ""
echo "Production:"
echo "  Project ID: ${GCP_PROJECT_ID_PROD}"
echo "  WIF Provider: ${PROD_WIF_PROVIDER}"
echo "  Service Account: ${PROD_SA_EMAIL}"
echo ""
echo "✅ Workflow file has been updated automatically!"
echo "💡 Review the changes with: git diff $WORKFLOW_FILE"
