# Generated by setup.sh on Fri Jan 23 17:40:22 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 3)

project_id          = "dev-rates"
region              = "us-central1"
environment         = "dev"
container_image_tag = "latest"
node_env            = "development"
use_fallback_image  = true  # Set to false after building/pushing the actual image to Artifact Registry
include_secrets = true # Set to true after creating secret values (see manual_steps_required output)

# CI/CD Configuration (disabled by default)
enable_cicd = true
github_owner = "AndresLGomezO"
github_repo  = "rates"
