# Generated by setup.sh on Tue Jan 27 06:49:33 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 3)

project_id          = "rates-production"
region              = "us-central1"
environment         = "dev"
container_image_tag = "dev-1769811299"
node_env            = "development"
use_fallback_image = false  # Set to false after building/pushing the actual image to Artifact Registry
include_secrets = true # Set to true after creating secret values (see manual_steps_required output)

# CI/CD Configuration (disabled by default)
enable_cicd = false
github_owner = null
github_repo  = "rates"
