# Generated by setup.sh on Sun Feb  1 13:38:09 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 3/4)

project_id            = "rates-production"
region                = "us-central1"
environment           = "dev"

# Initially deploy with fallback image (no secrets)
use_fallback_image = false
include_secrets = true

# Container image configuration
container_image_tag = "dev-1770043483"
ai_service_image_tag = "dev-1770043483"
ai_processor_image_tag = "dev-1770043483"
