# Generated by setup.sh on Sun Feb  1 09:14:20 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 2)

project_id        = "rates-production"
region            = "us-central1"
budget_amount     = 10
alert_email       = ""
