# Generated by setup.sh on Fri Jan 23 17:36:09 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 2)

project_id   = "dev-rates"
region       = "us-central1"
environments = ["dev", "prod"]

# Cost Guardrails Configuration
enable_budget_alerts = false
disable_unused_apis  = true
budget_amount        = 10

billing_account_id = "01847A-227A20-CD6FB1"
budget_alert_email = null
