# Generated by setup.sh on Tue Jan 27 06:42:13 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 2)

project_id   = "rates-production"
region       = "us-central1"
environments = ["dev", "prod"]

# Cost Guardrails Configuration
enable_budget_alerts = false
disable_unused_apis  = true
budget_amount        = 10

billing_account_id = "01847A-227A20-CD6FB1"
budget_alert_email = null
