# Generated by setup.sh on Sun Feb  1 09:11:07 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 1)

project_id         = "rates-production"
region             = "us-central1"
state_bucket_name  = "rates-terraform-state"
state_retention_days = 90
