# Generated by setup.sh on Fri Jan 23 17:33:39 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 1)

project_id         = "dev-rates"
region             = "us-central1"
state_bucket_name  = "rates-terraform-state"
state_retention_days = 90
