# Generated by setup.sh on Sun Jan 25 20:19:39 -05 2026
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 4)
# ⚠️  PRODUCTION ENVIRONMENT

project_id          = "rates-production"
region              = "us-central1"
environment         = "prod"
container_image_tag = "latest"
node_env            = "production"
use_fallback_image  = true  # Set to false after building/pushing the actual image to Artifact Registry
include_secrets     = false # Set to true after creating secret values (see manual_steps_required output)

# IMPORTANT: Set to true only after reviewing terraform plan
deployment_approved = false

# CI/CD Configuration (disabled by default)
enable_cicd           = false
github_owner          = null
github_repo           = "rates"
cicd_require_approval = true
