#!/usr/bin/env bash

# ============================================================================
# PHASE 2: FOUNDATION LAYER
# ============================================================================
# Purpose: Create foundational GCP and Firebase infrastructure
# Creates: APIs, service accounts, Artifact Registry, Firebase services
# Dependencies: All libraries
# ============================================================================

set -euo pipefail

phase_2_foundation() {
    print_header "PHASE 2: Foundation Layer"
    
    cat <<EOF
This phase creates the foundational infrastructure for the application:

  • Required GCP APIs
  • Service accounts and IAM bindings
  • Artifact Registry for Docker images
  • Firebase services (Auth, Firestore, Web App)

Terraform State: gs://${STATE_BUCKET_NAME}/foundation/

EOF

    if ! confirm "Begin foundation deployment?"; then
        print_warning "Foundation skipped"
        return 1
    fi

    # Verify state bucket exists
    if ! gcloud_verify_bucket "${STATE_BUCKET_NAME}"; then
        return 1
    fi

    local foundation_dir="${SCRIPT_DIR}/environments/foundation"
    
    if [[ ! -d "${foundation_dir}" ]]; then
        print_error "Foundation directory not found: ${foundation_dir}"
        return 1
    fi
    
    cd "${foundation_dir}"

    # -------------------------------------------------------------------------
    # Create terraform.tfvars
    # -------------------------------------------------------------------------
    print_section "Generating Configuration"
    
    local budget_amount="${BUDGET_AMOUNT:-10}"
    local alert_email="${BUDGET_ALERT_EMAIL:-}"
    
    cat > terraform.tfvars <<EOF
# Generated by setup.sh on $(date)
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 2)

project_id        = "${PROJECT_ID}"
region            = "${REGION}"
budget_amount     = ${budget_amount}
alert_email       = "${alert_email}"
EOF
    
    print_success "Created terraform.tfvars"

    # -------------------------------------------------------------------------
    # Terraform Workflow
    # -------------------------------------------------------------------------
    tf_init "${foundation_dir}" "true"
    tf_plan "${foundation_dir}" "tfplan"
    
    # Use retry logic for foundation (complex with many APIs)
    if ! tf_apply_with_retry "${foundation_dir}" "tfplan" "Foundation"; then
        cd "${SCRIPT_DIR}"
        return 1
    fi

    # -------------------------------------------------------------------------
    # Setup Firebase Services
    # -------------------------------------------------------------------------
    print_section "Setting up Firebase Services"
    
    cat <<EOF
Firebase services will be initialized and configured:
  • Firebase project initialization
  • Firebase Authentication
  • Firestore database
  • Firebase web app
  • Firestore security rules

EOF

    if confirm "Setup Firebase services now?"; then
        if firebase_setup_all "${PROJECT_ID}" "${REGION}"; then
            print_success "Firebase services configured!"
        else
            print_warning "Firebase setup had some issues"
            print_info "You can complete Firebase setup manually in the console"
        fi
    else
        print_info "Skipping Firebase setup"
        print_info "You can run Firebase setup later manually"
    fi

    # -------------------------------------------------------------------------
    # Show Outputs
    # -------------------------------------------------------------------------
    tf_show_outputs "${foundation_dir}"

    cd "${SCRIPT_DIR}"
    
    CURRENT_PHASE=2
    save_configuration
    
    print_success "Phase 2 (Foundation) complete!"
    
    if confirm "Proceed to Phase 3 (Application - Dev)?"; then
        return 0
    else
        print_info "You can resume later with: ./setup.sh --phase 3"
        return 1
    fi
}
