#!/usr/bin/env bash

# ============================================================================
# PHASE 3: APPLICATION LAYER (ENVIRONMENT-AGNOSTIC)
# ============================================================================
# Purpose: Deploy Cloud Run applications for a specific environment
# Creates: Cloud Run services, secrets, domain mappings
# Dependencies: All libraries
# ============================================================================

set -euo pipefail

phase_3_application() {
    local env="${1:-dev}"
    local env_name="${2:-Development}"
    
    print_header "PHASE 3: Application Layer (${env_name})"
    
    cat <<EOF
This phase deploys the application infrastructure for ${env_name}:

  • Cloud Run services (API, App)
  • Secret Manager secrets
  • Service account permissions
  • Container image deployment

Terraform State: gs://${STATE_BUCKET_NAME}/application/${env}/

EOF

    if [[ "${env}" == "prod" ]]; then
        print_warning "⚠️  PRODUCTION DEPLOYMENT"
        if ! confirm "Deploy to PRODUCTION environment?" "n"; then
            print_warning "Production deployment cancelled"
            return 1
        fi
    fi

    if ! confirm "Begin ${env_name} deployment?"; then
        print_warning "${env_name} deployment skipped"
        return 1
    fi

    # Verify state bucket exists
    if ! gcloud_verify_bucket "${STATE_BUCKET_NAME}"; then
        return 1
    fi

    local app_dir="${SCRIPT_DIR}/environments/application/${env}"
    
    if [[ ! -d "${app_dir}" ]]; then
        print_error "Application directory not found: ${app_dir}"
        return 1
    fi
    
    cd "${app_dir}"

    # -------------------------------------------------------------------------
    # Create terraform.tfvars
    # -------------------------------------------------------------------------
    print_section "Generating Configuration"
    
    cat > terraform.tfvars <<EOF
# Generated by setup.sh on $(date)
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 3/4)

project_id            = "${PROJECT_ID}"
region                = "${REGION}"
environment           = "${env}"

# Initially deploy with fallback image (no secrets)
use_fallback_image    = true
include_secrets       = false

# Container image configuration
container_image_tag   = "latest"
EOF
    
    print_success "Created terraform.tfvars"

    # -------------------------------------------------------------------------
    # Terraform Workflow
    # -------------------------------------------------------------------------
    tf_init "${app_dir}" "true"
    tf_plan "${app_dir}" "tfplan"
    
    if [[ "${env}" == "prod" ]]; then
        print_warning "⚠️  PRODUCTION DEPLOYMENT"
        if ! confirm "Apply this plan to PRODUCTION?" "n"; then
            rm -f tfplan
            cd "${SCRIPT_DIR}"
            return 1
        fi
        if ! confirm "Are you absolutely sure?" "n"; then
            rm -f tfplan
            cd "${SCRIPT_DIR}"
            return 1
        fi
    fi
    
    if ! tf_apply_with_retry "${app_dir}" "tfplan" "${env_name} Application"; then
        cd "${SCRIPT_DIR}"
        return 1
    fi

    # -------------------------------------------------------------------------
    # Create Secrets
    # -------------------------------------------------------------------------
    print_section "Post-Deployment: Secret Management"
    
    cat <<EOF
Secrets need to be created for the ${env_name} environment:
  • Firebase service account key
  • Nonce secret for security

EOF

    if confirm "Create secrets for ${env} environment?"; then
        if secrets_create_for_env "${env}" "${PROJECT_ID}" "${DEFAULT_PROJECT_ID}"; then
            print_success "Secrets created successfully!"
        else
            print_error "Secret creation failed"
            cd "${SCRIPT_DIR}"
            return 1
        fi
    else
        print_warning "Secrets not created - services may not function correctly"
    fi

    # -------------------------------------------------------------------------
    # Build and Push Docker Images
    # -------------------------------------------------------------------------
    print_section "Post-Deployment: Container Images"
    
    cat <<EOF
Would you like to build and push Docker images now?

This will:
  • Build API and App containers from source
  • Push to Artifact Registry (${REGION})
  • Tag as 'latest'

If you skip this, you can build/push images later.

EOF

    if confirm "Build and push Docker images?"; then
        if docker_build_and_push "${env}" "${PROJECT_ID}" "${REGION}" "latest"; then
            print_success "Docker images built and pushed!"
            
            # Update Cloud Run services
            if confirm "Update Cloud Run services with new images and secrets?"; then
                if secrets_update_cloud_run "${env}" "latest"; then
                    print_success "Cloud Run services updated!"
                else
                    print_error "Cloud Run update failed"
                fi
            fi
        else
            print_error "Docker build/push failed"
            print_info "You can build and push images manually later"
        fi
    else
        print_info "Skipping Docker build/push"
        print_info "Services will use fallback images until you deploy custom images"
    fi

    # -------------------------------------------------------------------------
    # Show Outputs
    # -------------------------------------------------------------------------
    tf_show_outputs "${app_dir}"

    cd "${SCRIPT_DIR}"
    
    return 0
}
