#!/usr/bin/env bash

# ============================================================================
# PHASE 5: CI/CD INTEGRATION
# ============================================================================
# Purpose: Setup Cloud Build triggers for CI/CD (Optional)
# Creates: Cloud Build triggers for automated deployments
# Dependencies: All libraries
# ============================================================================

set -euo pipefail

phase_5_cicd() {
    print_header "PHASE 5: CI/CD Integration (Optional)"
    
    cat <<EOF
This phase sets up CI/CD integration using Cloud Build:

  • Cloud Build triggers
  • Automated builds on code changes
  • Automated deployments to dev/prod

Terraform State: gs://${STATE_BUCKET_NAME}/cicd/

This phase is OPTIONAL. You can skip it and deploy manually.

EOF

    if ! confirm "Setup CI/CD integration?" "n"; then
        print_info "CI/CD integration skipped"
        print_info "You can setup CI/CD later with: ./setup.sh --phase 5"
        CURRENT_PHASE=5
        save_configuration
        return 0
    fi

    # Verify state bucket exists
    if ! gcloud_verify_bucket "${STATE_BUCKET_NAME}"; then
        return 1
    fi

    local cicd_dir="${SCRIPT_DIR}/environments/cicd"
    
    if [[ ! -d "${cicd_dir}" ]]; then
        print_warning "CI/CD directory not found: ${cicd_dir}"
        print_info "CI/CD integration not available in this setup"
        CURRENT_PHASE=5
        save_configuration
        return 0
    fi
    
    cd "${cicd_dir}"

    # -------------------------------------------------------------------------
    # Create terraform.tfvars
    # -------------------------------------------------------------------------
    print_section "Generating Configuration"
    
    cat > terraform.tfvars <<EOF
# Generated by setup.sh on $(date)
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 5)

project_id        = "${PROJECT_ID}"
region            = "${REGION}"

# GitHub repository configuration (update as needed)
# repository_name   = "owner/repo"
# branch_name       = "main"
EOF
    
    print_success "Created terraform.tfvars"
    print_warning "Please update terraform.tfvars with your GitHub repository details"

    # -------------------------------------------------------------------------
    # Terraform Workflow
    # -------------------------------------------------------------------------
    if confirm "Continue with CI/CD deployment?"; then
        tf_init "${cicd_dir}" "true"
        tf_plan "${cicd_dir}" "tfplan"
        
        if ! tf_apply_with_retry "${cicd_dir}" "tfplan" "CI/CD"; then
            cd "${SCRIPT_DIR}"
            return 1
        fi

        # Show Outputs
        tf_show_outputs "${cicd_dir}"
    else
        print_info "CI/CD deployment cancelled"
    fi

    cd "${SCRIPT_DIR}"
    
    CURRENT_PHASE=5
    save_configuration
    
    print_success "Phase 5 (CI/CD) complete!"
    
    if confirm "Proceed to Phase 6 (Cost Guardrails)?"; then
        return 0
    else
        print_info "You can resume later with: ./setup.sh --phase 6"
        return 1
    fi
}
