#!/usr/bin/env bash

# ============================================================================
# PHASE 1: BOOTSTRAP LAYER
# ============================================================================
# Purpose: Create foundational infrastructure for Terraform state management
# Creates: GCS bucket for state, versioning, lifecycle policies
# Dependencies: gcloud.sh, terraform.sh, logging.sh, prompts.sh, config.sh
# ============================================================================

set -euo pipefail

phase_1_bootstrap() {
    print_header "PHASE 1: Bootstrap Layer"
    
    cat <<EOF
This phase creates the foundational infrastructure for Terraform state
management:

  • GCS bucket for Terraform state (${STATE_BUCKET_NAME})
  • Bucket versioning and lifecycle policies
  • Required APIs (Storage, Service Usage)

State Location: gs://${STATE_BUCKET_NAME}/bootstrap/

EOF

    if ! confirm "Begin bootstrap deployment?"; then
        print_warning "Bootstrap skipped"
        return 1
    fi

    local bootstrap_dir="${SCRIPT_DIR}/environments/bootstrap"
    
    # Check if bootstrap directory exists
    if  [[ ! -d "${bootstrap_dir}" ]]; then
        print_error "Bootstrap directory not found: ${bootstrap_dir}"
        print_info "Please ensure Terraform files are in place"
        return 1
    fi
    
    cd "${bootstrap_dir}"

    # -------------------------------------------------------------------------
    # Create terraform.tfvars
    # -------------------------------------------------------------------------
    print_section "Generating Configuration"
    
    cat > terraform.tfvars <<EOF
# Generated by setup.sh on $(date)
# Source: docs/IMPLEMENTATION_PLAN.md (Phase 1)

project_id         = "${PROJECT_ID}"
region             = "${REGION}"
state_bucket_name  = "${STATE_BUCKET_NAME}"
state_retention_days = 90
EOF
    
    print_success "Created terraform.tfvars"

    # -------------------------------------------------------------------------
    # Configure backend for bootstrap
    # -------------------------------------------------------------------------
    print_section "Configuring Terraform Backend"
    
    print_step "Configuring local backend for bootstrap..."
    
    # Backup existing backend.tf if it exists and is different
    if [[ -f "backend.tf" ]] && ! grep -q "backend \"local\"" backend.tf 2>/dev/null; then
        cp backend.tf backend.tf.gcs.backup
        print_info "Backed up existing backend.tf"
    fi
    
    # Always use local backend for bootstrap (as per bootstrap/README.md)
    cat > backend.tf <<EOF
# ============================================================================
# BOOTSTRAP LAYER - BACKEND CONFIGURATION (LOCAL)
# ============================================================================
# Bootstrap always uses local backend (per README.md)
# State will be migrated to GCS after bucket is created
# Configured by setup.sh on $(date)

terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}
EOF
    print_success "Configured local backend for bootstrap"
    
    # Clean up old Terraform backend
    tf_clean_backend "${bootstrap_dir}"

    # -------------------------------------------------------------------------
    # Terraform Init
    # -------------------------------------------------------------------------
    tf_init "${bootstrap_dir}" "true"

    # -------------------------------------------------------------------------
    # Terraform Plan
    # -------------------------------------------------------------------------
    tf_plan "${bootstrap_dir}" "tfplan"

    # -------------------------------------------------------------------------
    # Terraform Apply
    # -------------------------------------------------------------------------
    if ! confirm "Apply this plan?"; then
        print_warning "Apply cancelled"
        rm -f tfplan
        cd "${SCRIPT_DIR}"
        return 1
    fi
    
    print_section "Applying Infrastructure"
    print_step "Running terraform apply..."
    
    if terraform apply -input=false tfplan >> "${LOG_FILE}" 2>&1; then
        print_success "Bootstrap infrastructure created!"
        rm -f tfplan
    else
        # Check for "bucket already exists" error and import it
        local apply_error
        apply_error=$(tail -50 "${LOG_FILE}" 2>/dev/null)
        
        if echo "${apply_error}" | grep -qE "Error 409.*bucket.*already.*own|bucket.*already exists|Your previous request to create the named bucket succeeded"; then
            print_warning "Bucket already exists. Attempting to import..."
            
            local bucket_resource="google_storage_bucket.terraform_state"
            local bucket_id="${STATE_BUCKET_NAME}"
            
            print_step "Importing existing bucket into Terraform state..."
            if terraform import "${bucket_resource}" "${bucket_id}" >> "${LOG_FILE}" 2>&1; then
                print_success "Bucket imported successfully"
                
                # Re-plan and re-apply
                rm -f tfplan
                if tf_plan "${bootstrap_dir}" "tfplan"; then
                    if confirm "Apply the updated plan?"; then
                        if terraform apply -input=false tfplan >> "${LOG_FILE}" 2>&1; then
                            print_success "Bootstrap infrastructure created!"
                            rm -f tfplan
                        else
                            print_error "Terraform apply failed after import"
                            rm -f tfplan
                            cd "${SCRIPT_DIR}"
                            return 1
                        fi
                    else
                        print_warning "Apply cancelled"
                        rm -f tfplan
                        cd "${SCRIPT_DIR}"
                        return 1
                    fi
                fi
            else
                print_error "Failed to import bucket"
                print_info "You may need to import it manually:"
                print_info "  terraform import google_storage_bucket.terraform_state ${STATE_BUCKET_NAME}"
                rm -f tfplan
                cd "${SCRIPT_DIR}"
                return 1
            fi
        else
            print_error "Terraform apply failed"
            print_info "Check ${LOG_FILE} for details"
            rm -f tfplan
            cd "${SCRIPT_DIR}"
            return 1
        fi
    fi

    # -------------------------------------------------------------------------
    # Show Outputs
    # -------------------------------------------------------------------------
    tf_show_outputs "${bootstrap_dir}"
    
    # -------------------------------------------------------------------------
    # Migrate State to GCS
    # -------------------------------------------------------------------------
    print_section "Migrating State to GCS"
    
    cat <<EOF
The state bucket has been created. Now migrating Terraform state from
local storage to GCS for durability and team access.

EOF
    
    print_step "Updating backend configuration to GCS..."
    cat > backend.tf <<EOF
# ============================================================================
# BOOTSTRAP LAYER - BACKEND CONFIGURATION (GCS)
# ============================================================================
# Migrated to GCS by setup.sh on $(date)

terraform {
  backend "gcs" {
    bucket = "${STATE_BUCKET_NAME}"
    prefix = "bootstrap/"
  }
}
EOF
    
    print_step "Migrating state to GCS..."
    if terraform init -migrate-state >> "${LOG_FILE}" 2>&1; then
        print_success "State migrated to GCS"
        rm -f terraform.tfstate terraform.tfstate.backup backend.tf.gcs.backup
    else
        print_warning "State migration failed (this is OK if bucket was just created)"
        print_info "Local state file preserved"
        print_info "State will be in GCS on next terraform init"
    fi

    cd "${SCRIPT_DIR}"
    
    CURRENT_PHASE=1
    save_configuration
    
    print_success "Phase 1 (Bootstrap) complete!"
    
    if confirm "Proceed to Phase 2 (Foundation)?"; then
        return 0
    else
        print_info "You can resume later with: ./setup.sh --phase 2"
        return 1
    fi
}
